// alert("Hi");

let buttonColours = ["red", "blue", "green", "yellow"];
let gamePattern = []; // store the random color generated by computer
let userClickedPattern = []; // store the selected button color by user

let level = 0;
var keyPressed = false;

$(document).keypress(function () {
  if (!keyPressed) {
    nextSequence();
    keyPressed = true;
  }
});

// user selection
$(".btn").click(function () {
  // Handler function to be triggered when any button is clicked
  var userChosenColor = $(this).attr("id");
  userClickedPattern.push(userChosenColor);
  console.log(userClickedPattern);
  playSound(userChosenColor);
  animatePress(userChosenColor);
  checkAnswer();
});

// computer generate
function nextSequence() {
  level++;
  $("#level-title").text("Level " + level);
  const randomNumber = Math.floor(Math.random() * 4);
  var randomChosenColour = buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);
  $("#" + randomChosenColour)
    .fadeOut(30)
    .fadeIn(50)
    .fadeOut(30)
    .fadeIn(50);
  console.log(gamePattern);
  playSound(randomChosenColour);
}

function checkAnswer() {
  if (userClickedPattern.length === gamePattern.length) {
    if (JSON.stringify(userClickedPattern) === JSON.stringify(gamePattern)) {
      console.log("your correct");
      setTimeout(() => {
        userClickedPattern = [];
        nextSequence();
      }, 1000);
    } else {
      wrongSelected();
    }
  }
}


function playSound(name) {
  var clickedAudio = "sounds/" + name + ".mp3";
  var audio = new Audio(clickedAudio);
  audio.play();
}

function animatePress(currentColour) {
  $("#" + currentColour).addClass("pressed");

  setTimeout(() => {
    $("#" + currentColour).removeClass("pressed");
  }, 100);
}

function wrongSelected() {
  console.log("your wrong");
  userClickedPattern = [];
  playSound("wrong");
  $('body').addClass("game-over");
  setTimeout(() => {
    $('body').removeClass("game-over");
  }, 200);
  // Restart the game or show a message to the user indicating they were wrong
  $('h1').text("Game Over, Press Any Key to Restart")
  startOver()

}

function startOver() {
  level = 0;
  gamePattern = [];
      keyPressed = false;
}
